apiVersion: v1
kind: Service
metadata:
  name: pipeline-demo
spec:
  ports:
  - name: pipeline-demo-svr
    port: 40080
    nodePort: 31888
    targetPort: 40080
  selector:
    app: pipeline-demo
  type: NodePort
